# heritage-exp-app Secure Configuration

sales-prc-app:
  client-id: "![kSVvZmLTTFDXcZlgGqWq66Qz1alSBj+pebPS5nRIwUDnLujX6UpY1Q==]"
  client-secret: "![6I+ftRZLtbuDr2bzXN/+o5Lk9ATqF2udGmJhj9IbJ0P9Wp4AYkEA2g==]"